// Auth actions
export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const USERNAME_CHANGED = 'username_changed'
export const LOGIN_USER = 'login_user'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const REGISTER_USER = 'register_user'
export const REGISTER_USER_SUCCESS = 'register_user_success'
export const REGISTER_USER_FAIL = 'register_user_fail'
export const LOGOUT_USER = 'logout_user'

// Stock actions
export const TICKER_CHANGED = 'ticker_changed'
export const GET_USER_STOCKS = 'get_user_stocks'
export const GET_USER_STOCKS_SUCCESS = 'get_user_stocks_success'
export const GET_USER_STOCKS_FAIL = 'get_user_stocks_fail'
export const GET_NEW_STOCK_INFO = 'get_new_stock_info'
export const GET_NEW_STOCK_INFO_SUCCESS = 'get_new_stock_info_success'
export const GET_NEW_STOCK_INFO_FAIL = 'get_new_stock_info_fail'
export const GET_NEW_STOCK_SENTIMENT = 'get_new_stock_sentiment'
export const GET_NEW_STOCK_SENTIMENT_SUCCESS = 'get_new_stock_sentiment_success'
